### ISSUE TITLE
Define a PURL specification for crypto assets

### ISSUE THREAD

**Issue by n1ckl0sk0rtge** [IBM/CBOM#13]
Define a [PURL specification](https://github.com/package-url/purl-spec) for crypto assets.

Possible formats:
- algorithm: `pkg:crypto/algorithm/<algorithm>@<oid>` (pkg:crypto/algorithm/Kybe@oid:1.3.6.1.4.1.2.267.8)
- certificate: `pkg:crypto/certificate/<id>@<algo:hash>` (for X509 the id could be CN, or other readable id. With `hash` being the hash calculated over the file) pkg:crypto/certificate/github@sha256:f323...)
- protocol: `pkg:crypto/protocol/<name>@<version>` (pkg:crypto/protocol/tls@1.3)
- relatedCryptoMaterial: `pkg:crypto/relatedCryptoMaterial/<type>@<algo:hash>` (With `hash` being the hash calculated over the value)

Using qualifiers for the crypto-properties to further specify the component related purl.

**Comment by GeroDittmann** [comment]
As discussed yesterday, this use of something that looks like a PURL but doesn't actually point to any repository seems a bit unfortunate. How about using something like `oid:<oid>` instead? (We'd have to think of alternatives for the other types.)

This is about values for the `bom-ref` fields, is it?

**Comment by n1ckl0sk0rtge** [comment]
Suggestion: Add a field called `standardName` to be able to set standard names from IANA or an RFC for a specific algorithm

**Comment by bhess** [comment]
Closing with the upstream to [CycloneDX 1.6](https://github.com/CycloneDX/specification/releases/tag/1.6).
