### ISSUE TITLE
IKEv2 RFC 9370: dh->ke

### ISSUE THREAD

**Issue by GeroDittmann** [IBM/CBOM#34]
"This document updates RFC 7296 by renaming a Transform Type 4 from "Diffie-Hellman Group (D-H)" to "Key Exchange Method (KE)"
https://www.rfc-editor.org/rfc/rfc9370.html

This should probably be adapted in `ikev2TransformTypes`?

**Comment by bhess** [comment]
Thanks Gero, updated in https://github.com/IBM/CBOM/commit/1babb2b3b7e008620886a7b716b6924e9cba7c3d, along with adding an "auth" field.
