### ISSUE TITLE
Processing and viewing the CBOM

### ISSUE THREAD

**Issue by kkretsch** [IBM/CBOM#40]
I miss some links to existing or upcoming frontends to work with or visualize the resulting CBOM file. Could we have some chapter in the README.md for referencing any current tools for this?

**Comment by bhess** [comment]
Thank you for your feedback @kkretsch and your interest in CBOM! I've added commit https://github.com/IBM/CBOM/commit/26656c1dcc2e8850b291e3c01e75a66c063e9f1b which includes references to tooling related to CBOM.
