### ISSUE TITLE
Security levels are associated with algorithms, so they should be part of algorithm properties

### ISSUE THREAD

**Issue by n1ckl0sk0rtge** [IBM/CBOM#7]
In the current CBOM definition, both security levels (`classicalSecurityLevel` and `nistQuantumSecurityLevel`) are part of the general object `cryptoProperties`. But these values are tightly coupled to a cryptographic algorithm. In this sense, they should be part of `algorithmProperties`.

```json
"name" : "KeyEncapsulation.Kyber",
"type" : "crypto-asset",
"bom-ref" : "alg:KeyEncapsulation.Kyber"
"cryptoProperties" : {
  "assetType" : "algorithm",
  "algorithmProperties" : {
    "primitive" : "keyagree",
    "variant" : "Kyber-1024",
    "implementationPlatform": "x86_64",
    "certificationLevel": "none",
    "nistQuantumSecurityLevel" : 5
  },
  "oid" : "1.3.6.1.4.1.2.267.8"
}
```

**Comment by bhess** [comment]
Thinking about if the security levels may be useful outside the algorithm asset type... Protocols (e.g. tls cipher suites) may be associated with a security level as well.

**Comment by n1ckl0sk0rtge** [comment]
Yes, that is true, but I think at the moment the security levels we capture are only related to and used for algorithms, as I understand it. Maybe we could introduce a general security strength with values like `insecure`, `weak` and `secure`, which could then also be used for protocols and other assets.
